package:
  name: multi-vis
  version: 0.1.4

source:
  path: ../

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  build:
    - setuptools
    - python >=3.5
    - numpy
    - pandas
    - matplotlib
    - seaborn
    - networkx
    - scipy
    - scikit-learn
    - tqdm

  run:
    - python >=3.5
    - numpy
    - pandas
    - matplotlib
    - seaborn
    - networkx
    - scipy
    - scikit-learn
    - tqdm

about:
  home: https://github.com/brettChapman
  license: MIT License
  summary: "multi-vis is a data visualisation package that produces both static and interactive visualisations targeted towards the Omics community."

