package:
  name: multivis
  version: 0.4.4

source:
  path: ../

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  build:
    - setuptools
    - python >=3.5
    - numpy >=1.12
    - pandas==0.25.1
    - matplotlib==3.1.1
    - seaborn==0.9.0
    - networkx==2.3.0
    - scipy==1.3.1
    - scikit-learn==0.21.3
    - tqdm==4.36.1
    - xlrd==1.2.0

  run:
    - python >=3.5
    - numpy >=1.12
    - pandas==0.25.1
    - matplotlib==3.1.1
    - seaborn==0.9.0
    - networkx==2.3.0
    - scipy==1.3.1
    - scikit-learn==0.21.3
    - tqdm==4.36.1
    - xlrd==1.2.0

about:
  home: https://github.com/brettChapman
  license: MIT License
  summary: "Multivis is a data visualisation package that produces both static and interactive visualisations targeted towards the Omics community."

