package:
  name: multivis
  version: 0.5.3

source:
  path: ../

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  build:
    - setuptools
    - python >=3.5
    - numpy==1.20.2
    - pandas==1.2.4
    - matplotlib==3.4.1
    - seaborn==0.11.1
    - networkx==2.4.0
    - statsmodels==0.10.1
    - scikits-bootstrap==1.0.1
    - scipy==1.6.3
    - scikit-learn==0.24.2
    - tqdm==4.36.1
    - xlrd==1.2.0

  run:
    - python >=3.5
    - numpy==1.20.2
    - pandas==1.2.4
    - matplotlib==3.4.1
    - seaborn==0.11.1
    - networkx==2.4.0
    - statsmodels==0.10.1
    - scikits-bootstrap==1.0.1
    - scipy==1.6.3
    - scikit-learn==0.24.2
    - tqdm==4.36.1
    - xlrd==1.2.0

about:
  home: https://github.com/brettChapman
  license: MIT License
  summary: "Multivis is a data visualisation package that produces both static and interactive visualisations targeted towards the Omics community."

